### ISSUE TITLE
Dev tools support

### ISSUE THREAD

**Issue by k-bx** [anmolitor/protoc-gen-elm#267]
Was there any luck supporting something like https://github.com/SafetyCulture/grpc-web-devtools ?

**Comment by andreasewering** [comment]
Interesting. I'll take a look if I can make it work.

**Comment by k-bx** [comment]
@andreasewering sorry to ping, but did you have a chance to check it out?

**Comment by andreasewering** [comment]
I actually have a plan how we can support this now:

Below the sketched implementation, the critical parts have already been tested manually:

From the user side of this plugin:
- You will need to use a bundler like webpack or vite
- You will set a flag which will instruct protoc-gen-elm to emit additional debug helpers
- You will import a generated dev-tools.js file into your index.js file or include it in your index.html

The generated dev-tools.js file will do the following:
1. Set up a XMLHttpRequest interceptor by monkeypatching the prototype or the constructor. We can collect url, request body, response headers and response body this way.
2. Convert the request and response bodies into integer arrays from their byte representation to be able to pass them through an Elm port.
3. Send the bodies through an Elm port to a generated Elm worker which is imported in the dev-tools.js file (this is why you will need a bundler).
4. The worker will call the associated decode functions for the called method, which we can determine based on the requested url.
5. The worker encodes the Elm data type into JSON using this canonical mapping https://protobuf.dev/programming-guides/proto3/#json (we need to generate JSON Encoders here, which may be a feature we could also make available under a different flag)
6. The worker sends the JSON via a port back to Javascript (as Json.Encode.Value).
7. The Javascript Handler can now emit this grpc call to the dev tools (we have collected all data about the request, in readable json format).

So how do we communicate this to the grpc-dev-tools extension?

1. We generate a "client" per grpc service:

```
const client = {
  client_: {
    rpcCall: (method, req, metadata, info, callback) => {
      callback(responseObjectFromElm);
    },
  },
};
```

This client is then wrapped by the dev tools similar to our XMLHttpRequest monkeypatching.
So when we then call `client.client_.rpcCall`, the extension picks the data up and then calls our implementation, similar with the callback.
Our XMLHttpRequest interceptor therefore just needs to take the appropriate client based on the url and call rpcCall on it with the intercepted/decoded data.

... this may take a while to implement, but its possible!

**Comment by k-bx** [comment]
Sounds good. I'd love to test this out once this is ready!

**Comment by andreasewering** [comment]
This is implemented and available in version 3.4.0.

Feel free to try it out. I added dev-tools integration to the vite-js example in this repository and it seems to work fine.
It is probably a little rough around the edges, I haven't looked into how to report errors to the plugin correctly for example, but for most use cases it should already help a lot.

The plugin as a consequence now supports the canonical JSON encoding (for the most part, I think some well-known types are missing, timestamp iso encoding is implemented though ✅ ). Decoding is not added yet, since it isn't necessary for the dev tools.

**Comment by anmolitor** [comment]
I'll keep this issue open since the dev tools support is still a bit buggy - when firing multiple requests concurrently, the requests/responses might swap and errors are not handled so far.

**Comment by anmolitor** [comment]
I stabilized the support in 4.0.0.
Concurrent request should hopefully work (please report any issues).
Http and grpc errors are caught and should produce helpful errors in the grpc-web extension.
